const palette={"服务业主导型":"#287271","工业主导型":"#d17b45","农业比重较高型":"#829b4b","均衡发展型":"#7766a6","大型经济体":"#174d43","中型经济体":"#d5a13d","小型经济体":"#a99f91"};
const labels=["常住人口","户籍人口","人口密度","平均工资","GDP","人均GDP","GDP增长率","第一产业占比","第二产业占比","第三产业占比","预算收入","预算支出","规上企业"];
const map=L.map("map",{zoomControl:false}).setView([30.9,112.9],7);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap",opacity:.62}).addTo(map);
let data=null,index=null,layer=null,chart=null;const el=id=>document.getElementById(id);const unique=values=>[...new Set(values)];const option=value=>`<option value="${value}">${value}</option>`;const formatNumber=value=>{const number=Number(value);if(!Number.isFinite(number))return"-";return new Intl.NumberFormat("zh-CN",{maximumFractionDigits:4}).format(number)};
function scoreColor(value){const v=Math.max(0,Math.min(1,Number(value||0)));if(v>=.8)return"#174d43";if(v>=.6)return"#4d876b";if(v>=.4)return"#d5a13d";if(v>0)return"#c9654b";return"#d7d1c7"}
function rankColor(rank){if(rank<=3)return"#174d43";if(rank<=6)return"#4d876b";if(rank<=9)return"#d5a13d";return"#c9654b"}
function color(feature){const p=feature.properties;if(p.is_anchor)return"#742b3b";if(p.mode==="ranking")return rankColor(Number(p.model_rank||12));return p.mode==="comparison"?scoreColor(p.raw_score):(palette[p.prediction]||"#6d7775")}
function style(feature){return{color:"#fffdf8",weight:2,fillColor:color(feature),fillOpacity:.84}}
function visible(feature){const p=feature.properties,min=Number(el("confidenceRange").value);const score=p.mode==="comparison"?Number(p.raw_score||0):p.mode==="ranking"?Number(p.ranking_score||0):Number(p.normalized_confidence||0);const agreementAllowed=p.mode==="ranking"||!el("agreementOnly").checked||p.model_agreement===true;return p.is_anchor||score>=min&&agreementAllowed}
function point(feature,latlng){return L.circleMarker(latlng,{radius:12,fillColor:color(feature),fillOpacity:.9,color:"#fff",weight:2})}
function render(){if(!data)return;if(layer)layer.remove();const filtered={...data,features:data.features.filter(visible)};layer=L.geoJSON(filtered,{style,pointToLayer:point,onEachFeature:(feature,item)=>{const p=feature.properties;const tip=p.mode==="ranking"?`${p.city} · 模型第 ${p.model_rank} 名`: `${p.city} · ${p.prediction||"无结果"}`;item.bindTooltip(tip);item.on("click",()=>details(p))}}).addTo(map);if(layer.getBounds().isValid())map.fitBounds(layer.getBounds().pad(.12));legend();overview()}
function legend(){if(data?.metadata?.mode==="comparison"){el("legend").innerHTML="<strong>模型支持分数</strong><div><i style='background:#174d43'></i>≥ 0.80</div><div><i style='background:#4d876b'></i>0.60–0.79</div><div><i style='background:#d5a13d'></i>0.40–0.59</div><div><i style='background:#c9654b'></i>&lt; 0.40</div><div><i style='background:#742b3b'></i>基准城市</div>";return}if(data?.metadata?.mode==="ranking"){el("legend").innerHTML="<strong>模型综合排名</strong><div><i style='background:#174d43'></i>第 1–3 名</div><div><i style='background:#4d876b'></i>第 4–6 名</div><div><i style='background:#d5a13d'></i>第 7–9 名</div><div><i style='background:#c9654b'></i>第 10–12 名</div>";return}const values=unique(data.features.map(f=>f.properties.prediction).filter(Boolean));el("legend").innerHTML=`<strong>重构类别</strong>${values.map(v=>`<div><i style="background:${palette[v]||"#657170"}"></i>${v}</div>`).join("")}`}
function overview(){el("cityDetails").hidden=true;el("emptyState").hidden=false;const m=data?.metadata||{};if(m.mode==="ranking"){const s=m.summary||{};const rows=[...data.features].sort((a,b)=>a.properties.model_rank-b.properties.model_rank);el("mapOverview").innerHTML=`<span>城市指标排名</span><p>${m.year} 年 · ${m.relation}</p><div class="summary-grid"><div><small>两两准确率</small><b>${(Number(s.pairwise_accuracy||0)*100).toFixed(1)}%</b></div><div><small>Spearman</small><b>${Number(s.spearman||0).toFixed(3)}</b></div><div><small>Top-3 重合</small><b>${s.top3_overlap??"-"}/3</b></div><div><small>平均名次误差</small><b>${Number(s.mean_absolute_rank_error||0).toFixed(2)}</b></div></div><h3>模型排行榜</h3><ol class="overview-ranking">${rows.map(x=>`<li data-city="${x.properties.city}"><b>${x.properties.model_rank}</b><span>${x.properties.city}</span><em>${Number(x.properties.ranking_score).toFixed(3)}</em></li>`).join("")}</ol><p class="hint">点击地图城市查看模型名次、真实名次及两两比较。</p>`;el("mapOverview").querySelectorAll("li[data-city]").forEach(item=>item.addEventListener("click",()=>{const feature=data.features.find(x=>x.properties.city===item.dataset.city);if(feature)details(feature.properties)}));return}const anchor=m.anchor?`，基准城市为${m.anchor}`:"";el("mapOverview").innerHTML=`<span>当前推理地图</span><p>${m.year||"-"} 年 · ${m.relation||m.mode||"-"}${anchor}</p><div class="overview-note">${m.mode==="comparison"?"颜色表示模型对“基准城市指标高于候选城市”的支持程度。":"颜色表示模型重构的城市类别。"}</div><p class="hint">点击地图中的城市查看模型分数、候选明细和数值属性。</p>`}
function details(p){el("emptyState").hidden=true;el("cityDetails").hidden=false;el("detailCity").textContent=p.city;el("detailYear").textContent=`${p.year||""} · ${p.relation||""}`;el("prediction").textContent=p.mode==="ranking"?`模型第 ${p.model_rank} 名`:p.prediction||"无结果";const c=Number(p.mode==="comparison"?p.raw_score:p.mode==="ranking"?p.ranking_score:p.normalized_confidence||0);el("confidenceLabel").textContent=p.mode==="comparison"?"模型支持分数":p.mode==="ranking"?"模型综合分":"候选内 softmax 分数";el("confidence").textContent=c.toFixed(4);el("confidenceMeter").style.width=`${c*100}%`;el("knownSplit").textContent=p.mode==="ranking"?`实际第 ${p.actual_rank} 名`:p.known_split||p.actual||"候选知识";el("agreement").textContent=p.mode==="ranking"?`${p.rank_difference>0?"低估 "+p.rank_difference:p.rank_difference<0?"高估 "+Math.abs(p.rank_difference):"一致"}`:p.model_agreement===true?"一致":p.model_agreement===false?"存在分歧":"未启用复核";const badge=el("confidenceBadge");badge.textContent=p.mode==="ranking"?`${p.model_rank}/12`:p.is_anchor?"anchor":c>=.8?"high":c>=.6?"medium":"low";badge.className=`confidence-badge ${c>=.8?"high":c>=.6?"medium":"low"}`;const rows=p.mode==="ranking"?(p.comparisons||[]):p.candidates||[];el("topK").innerHTML=rows.map((x,i)=>`<li><b>${i+1}</b><span>${x.opponent_city||x.category||x.tail}</span><em>${Number(x.pairwise_advantage??x.normalized??x.score??x.raw_score??0).toFixed(3)}</em></li>`).join("");if(p.mode==="ranking")el("comparisonFacts").innerHTML=`<div><small>原始指标值</small><strong>${formatNumber(p.actual_value)}</strong></div><div><small>真实名次</small><strong>${p.actual_rank??"-"} / 12</strong></div><div><small>预测胜场</small><strong>${p.predicted_wins??"-"} / 11</strong></div><div><small>两两准确率</small><strong>${(Number(p.pairwise_accuracy||0)*100).toFixed(1)}%</strong></div>`;else el("comparisonFacts").innerHTML=p.mode==="comparison"&&!p.is_anchor?`<div><small>基准值</small><strong>${formatNumber(p.head_value)}</strong></div><div><small>候选值</small><strong>${formatNumber(p.tail_value)}</strong></div><div><small>真实关系</small><strong>${p.ground_truth?"高于":"不高于"}</strong></div><div><small>候选排名</small><strong>${p.rank??"-"}</strong></div>`:"";radar(p.numeric_values||[])}
function radar(values){if(chart)chart.destroy();if(!values.length)return;const all=data.features.map(f=>f.properties.numeric_values||[]);const max=values.map((_,i)=>Math.max(...all.map(row=>Number(row[i]||0)),1));chart=new Chart(el("radar"),{type:"radar",data:{labels,datasets:[{data:values.map((v,i)=>Number(v||0)/max[i]),borderColor:"#174d43",backgroundColor:"rgba(23,77,67,.18)",pointBackgroundColor:"#d39a3d",borderWidth:2}]},options:{plugins:{legend:{display:false}},scales:{r:{min:0,max:1,ticks:{display:false},grid:{color:"rgba(23,77,67,.12"},pointLabels:{font:{size:9}}}}}})}
async function fetchJson(path){const response=await fetch(path,{cache:"no-store"});if(!response.ok)throw new Error(`${path} 未生成`);return response.json()}
function records(){const mode=el("modeSelect").value;return mode==="type"?index.type_maps:mode==="ranking"?(index.ranking_maps||[]):index.comparison_maps}
function updateSelectors(reset=true){const rows=records();if(reset){el("yearSelect").innerHTML=unique(rows.map(x=>x.year)).map(option).join("");el("relationSelect").innerHTML=unique(rows.map(x=>x.relation)).map(option).join("")}const comparison=el("modeSelect").value==="comparison";el("anchorLabel").hidden=!comparison;if(comparison){const candidates=rows.filter(x=>String(x.year)===el("yearSelect").value&&x.relation===el("relationSelect").value);el("anchorSelect").innerHTML=unique(candidates.map(x=>x.anchor)).map(option).join("")}}
async function loadSelected(){if(!index)return loadSingle();const mode=el("modeSelect").value,rows=records();const selected=rows.find(x=>String(x.year)===el("yearSelect").value&&x.relation===el("relationSelect").value&&(mode!=="comparison"||x.anchor===el("anchorSelect").value));if(!selected)throw new Error("没有对应地图数据");data=await fetchJson(selected.file);el("modelStatus").textContent=`${data.features.length} 城市 · ${data.metadata.mode}`;render()}
async function loadSingle(){data=await fetchJson("data.geojson");el("modeSelect").value=data.metadata?.mode||"type";el("yearSelect").innerHTML=option(data.metadata?.year||"-");el("relationSelect").innerHTML=option(data.metadata?.relation||data.metadata?.mode||"-");el("anchorSelect").innerHTML=option(data.metadata?.anchor||"-");el("anchorLabel").hidden=data.metadata?.mode!=="comparison";el("modelStatus").textContent=`${data.features.length} 城市 · ${data.metadata?.mode||"map"}`;render()}
async function initialise(){try{index=await fetchJson("index.json");updateSelectors(true);await loadSelected()}catch(_){index=null;await loadSingle()}}
function showError(error){el("modelStatus").textContent="数据未生成";el("legend").innerHTML=`<strong>${error.message}</strong>`}
el("confidenceRange").addEventListener("input",e=>{el("confidenceValue").textContent=Number(e.target.value).toFixed(2);render()});el("agreementOnly").addEventListener("change",render);el("modeSelect").addEventListener("change",()=>{updateSelectors(true);loadSelected().catch(showError)});el("yearSelect").addEventListener("change",()=>{updateSelectors(false);loadSelected().catch(showError)});el("relationSelect").addEventListener("change",()=>{updateSelectors(false);loadSelected().catch(showError)});el("anchorSelect").addEventListener("change",()=>loadSelected().catch(showError));el("reloadButton").addEventListener("click",()=>loadSelected().catch(showError));el("backOverview").addEventListener("click",overview);initialise().catch(showError);
